export const Errors = {
  required: 'sapin.required',
  isInteger: 'sapin.invalidInteger',
  isPositive: 'sapin.valueShouldBePositive',
  isNegative: 'sapin.valueShouldBeNegative',
  isGt: 'sapin.valueShouldBeGt',
  isGte: 'sapin.valueShouldBeGte',
  isLt: 'sapin.valueShouldBeLt',
  isLte: 'sapin.valueShouldBeLte',
  isEqualToField: 'sapin.valueShouldEqualField',
  isGtField: 'sapin.valueShouldBeGtField',
  isGteToField: 'sapin.valueShouldBeGteField',
  isLtField: 'sapin.valueShouldBeLtField',
  isLteToField: 'sapin.valueShouldBeLteField',
  withinRange: 'sapin.valueNotInRange',
  minLength: 'sapin.valueNotLongEnough',
  maxLength: 'sapin.valueTooLong',
  oneOf: 'sapin.oneOf',
  isEmail: 'sapin.invalidEmail',
  isOfTypeArray: 'sapin.notAnArray',
  isOfTypeObject: 'sapin.notAnObject',
  isNumber: 'sapin.invalidNumber',
  isOfTypeBool: 'sapin.notBoolean',
  isOfTypeString: 'sapin.notString',
  isOfTypeDate: 'sapin.invalidDate'
}
